CC = gcc
CSDIR = /cs/faculty/rich/public_html/class/cs170

EXECUTABLES = print4 hw p4a p4b p4c p4d adder iloop iloop_preempt

CFLAGS = -I$(CSDIR)/include -Wall

all: $(EXECUTABLES)

clean:
	rm -f core *.o $(EXECUTABLES) a.out

.SUFFIXES: .c .o
.c.o:
	$(CC) $(CFLAGS) -c $*.c


hw: hw.o
	$(CC) $(CFLAGS) -o hw hw.o -lpthread

print4: print4.o
	$(CC) $(CFLAGS) -o print4 print4.o -lpthread

p4a: p4a.o
	$(CC) $(CFLAGS) -o p4a p4a.o -lpthread

p4b: p4b.o
	$(CC) $(CFLAGS) -o p4b p4b.o -lpthread

p4c: p4c.o
	$(CC) $(CFLAGS) -o p4c p4c.o -lpthread

p4d: p4d.o
	$(CC) $(CFLAGS) -o p4d p4d.o -lpthread

adder: adder.o
	$(CC) $(CFLAGS) -o adder adder.o -lpthread

iloop: iloop.o
	$(CC) $(CFLAGS) -o iloop iloop.o -lpthread

iloop_preempt: iloop_preempt.o
	$(CC) $(CFLAGS) -o iloop_preempt iloop_preempt.o -lpthread

install:
	cp $(EXECUTABLES) ../bin.$(ARCH)
